package com.hoolai.chatmonitor.provider.process.dao.mybatis.vo;

import java.io.Serializable;


@SuppressWarnings("serial")
public class MsgIllegalWord  implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_words.id
     *
     * @mbg.generated
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_words.wrod
     *
     * @mbg.generated
     */
    private String wrod;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_words.status
     *
     * @mbg.generated
     */
    private Boolean status;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column m_words.id
     *
     * @return the value of m_words.id
     *
     * @mbg.generated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column m_words.id
     *
     * @param id the value for m_words.id
     *
     * @mbg.generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column m_words.wrod
     *
     * @return the value of m_words.wrod
     *
     * @mbg.generated
     */
    public String getWrod() {
        return wrod;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column m_words.wrod
     *
     * @param wrod the value for m_words.wrod
     *
     * @mbg.generated
     */
    public void setWrod(String wrod) {
        this.wrod = wrod;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column m_words.status
     *
     * @return the value of m_words.status
     *
     * @mbg.generated
     */
    public Boolean getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column m_words.status
     *
     * @param status the value for m_words.status
     *
     * @mbg.generated
     */
    public void setStatus(Boolean status) {
        this.status = status;
    }


	       ////*******自定义开始********/
        //***********自定义结束****////
}
