package com.hoolai.chatmonitor.provider.process.client.vo;

import java.io.Serializable;
import java.util.Date;

import com.google.common.base.Strings;


@SuppressWarnings("serial")
public class MsgSuspicious  implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_suspicious.id
     *
     * @mbg.generated
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_suspicious.uid
     *
     * @mbg.generated
     */
    private Long uid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_suspicious.game_id
     *
     * @mbg.generated
     */
    private Long gameId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_suspicious.msg
     *
     * @mbg.generated
     */
    private String msg;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_suspicious.create_time
     *
     * @mbg.generated
     */
    private String createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_suspicious.status
     *
     * @mbg.generated
     */
    private Byte status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_suspicious.illegal_words
     *
     * @mbg.generated
     */
    private String illegalWords;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_suspicious.op_uid
     *
     * @mbg.generated
     */
    private Long opUid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column m_suspicious.id
     *
     * @return the value of m_suspicious.id
     *
     * @mbg.generated
     */
    
    
    private String gameUid;//游戏传过来的uid
    private String gameName;//游戏名称
    private String statusDes;//状态描述
    private String opAccount;//审核员账号
    
    
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column m_suspicious.id
     *
     * @param id the value for m_suspicious.id
     *
     * @mbg.generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column m_suspicious.uid
     *
     * @return the value of m_suspicious.uid
     *
     * @mbg.generated
     */
    public Long getUid() {
        return uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column m_suspicious.uid
     *
     * @param uid the value for m_suspicious.uid
     *
     * @mbg.generated
     */
    public void setUid(Long uid) {
        this.uid = uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column m_suspicious.game_id
     *
     * @return the value of m_suspicious.game_id
     *
     * @mbg.generated
     */
    public Long getGameId() {
        return gameId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column m_suspicious.game_id
     *
     * @param gameId the value for m_suspicious.game_id
     *
     * @mbg.generated
     */
    public void setGameId(Long gameId) {
        this.gameId = gameId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column m_suspicious.msg
     *
     * @return the value of m_suspicious.msg
     *
     * @mbg.generated
     */
    public String getMsg() {
        return msg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column m_suspicious.msg
     *
     * @param msg the value for m_suspicious.msg
     *
     * @mbg.generated
     */
    public void setMsg(String msg) {
        this.msg = msg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column m_suspicious.create_time
     *
     * @return the value of m_suspicious.create_time
     *
     * @mbg.generated
     */

    public String getCreateTime() {
    	 createTime = !Strings.isNullOrEmpty(createTime) && createTime.indexOf(".")>0?createTime.substring(0,createTime.indexOf(".")):createTime;
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column m_suspicious.create_time
     *
     * @param createTime the value for m_suspicious.create_time
     *
     * @mbg.generated
     */
    public void setCreateTime(String createTime) {
        this.createTime = !Strings.isNullOrEmpty(createTime) && createTime.indexOf(".")>0?createTime.substring(0,createTime.indexOf(".")):createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column m_suspicious.status
     *
     * @return the value of m_suspicious.status
     *
     * @mbg.generated
     */
    public Byte getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column m_suspicious.status
     *
     * @param status the value for m_suspicious.status
     *
     * @mbg.generated
     */
    public void setStatus(Byte status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column m_suspicious.illegal_words
     *
     * @return the value of m_suspicious.illegal_words
     *
     * @mbg.generated
     */
    public String getIllegalWords() {
        return illegalWords;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column m_suspicious.illegal_words
     *
     * @param illegalWords the value for m_suspicious.illegal_words
     *
     * @mbg.generated
     */
    public void setIllegalWords(String illegalWords) {
        this.illegalWords = illegalWords;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column m_suspicious.op_uid
     *
     * @return the value of m_suspicious.op_uid
     *
     * @mbg.generated
     */
    public Long getOpUid() {
        return opUid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column m_suspicious.op_uid
     *
     * @param opUid the value for m_suspicious.op_uid
     *
     * @mbg.generated
     */
    public void setOpUid(Long opUid) {
        this.opUid = opUid;
    }

	public String getGameUid() {
		return gameUid;
	}

	public void setGameUid(String gameUid) {
		this.gameUid = gameUid;
	}

	public String getGameName() {
		return gameName;
	}

	public void setGameName(String gameName) {
		this.gameName = gameName;
	}

	public String getStatusDes() {
		return statusDes;
	}

	public void setStatusDes(String statusDes) {
		this.statusDes = statusDes;
	}

	public String getOpAccount() {
		return opAccount;
	}

	public void setOpAccount(String opAccount) {
		this.opAccount = opAccount;
	}

    
    

	       ////*******自定义开始********/
    
        //***********自定义结束****////
}
