package com.hoolai.chatmonitor.open.dao.mybatis.vo;

import java.io.Serializable;

import java.util.Date;


@SuppressWarnings("serial")
public class AdminLog  implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin_log.log_id
     *
     * @mbg.generated
     */
    private Long logId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin_log.account
     *
     * @mbg.generated
     */
    private String account;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin_log.method
     *
     * @mbg.generated
     */
    private String method;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin_log.op_data
     *
     * @mbg.generated
     */
    private Date opData;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin_log.extend1
     *
     * @mbg.generated
     */
    private String extend1;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin_log.extend2
     *
     * @mbg.generated
     */
    private String extend2;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin_log.result
     *
     * @mbg.generated
     */
    private String result;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin_log.log_id
     *
     * @return the value of admin_log.log_id
     *
     * @mbg.generated
     */
    public Long getLogId() {
        return logId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin_log.log_id
     *
     * @param logId the value for admin_log.log_id
     *
     * @mbg.generated
     */
    public void setLogId(Long logId) {
        this.logId = logId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin_log.account
     *
     * @return the value of admin_log.account
     *
     * @mbg.generated
     */
    public String getAccount() {
        return account;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin_log.account
     *
     * @param account the value for admin_log.account
     *
     * @mbg.generated
     */
    public void setAccount(String account) {
        this.account = account;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin_log.method
     *
     * @return the value of admin_log.method
     *
     * @mbg.generated
     */
    public String getMethod() {
        return method;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin_log.method
     *
     * @param method the value for admin_log.method
     *
     * @mbg.generated
     */
    public void setMethod(String method) {
        this.method = method;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin_log.op_data
     *
     * @return the value of admin_log.op_data
     *
     * @mbg.generated
     */
    public Date getOpData() {
        return opData;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin_log.op_data
     *
     * @param opData the value for admin_log.op_data
     *
     * @mbg.generated
     */
    public void setOpData(Date opData) {
        this.opData = opData;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin_log.extend1
     *
     * @return the value of admin_log.extend1
     *
     * @mbg.generated
     */
    public String getExtend1() {
        return extend1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin_log.extend1
     *
     * @param extend1 the value for admin_log.extend1
     *
     * @mbg.generated
     */
    public void setExtend1(String extend1) {
        this.extend1 = extend1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin_log.extend2
     *
     * @return the value of admin_log.extend2
     *
     * @mbg.generated
     */
    public String getExtend2() {
        return extend2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin_log.extend2
     *
     * @param extend2 the value for admin_log.extend2
     *
     * @mbg.generated
     */
    public void setExtend2(String extend2) {
        this.extend2 = extend2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin_log.result
     *
     * @return the value of admin_log.result
     *
     * @mbg.generated
     */
    public String getResult() {
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin_log.result
     *
     * @param result the value for admin_log.result
     *
     * @mbg.generated
     */
    public void setResult(String result) {
        this.result = result;
    }


	       ////*******自定义开始********/
        //***********自定义结束****////
}
