package com.hoolai.chatmonitor.provider.user.dao.mybatis.mapper;

import com.hoolai.chatmonitor.provider.user.dao.mybatis.vo.UserFreeze;
import com.hoolai.chatmonitor.provider.user.dao.mybatis.vo.UserFreezeExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;


public interface UserFreezeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table u_freeze
     *
     * @mbg.generated
     */
    long countByExample(UserFreezeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table u_freeze
     *
     * @mbg.generated
     */
    int deleteByExample(UserFreezeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table u_freeze
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long uid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table u_freeze
     *
     * @mbg.generated
     */
    int insert(UserFreeze record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table u_freeze
     *
     * @mbg.generated
     */
    int insertSelective(UserFreeze record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table u_freeze
     *
     * @mbg.generated
     */
    List<UserFreeze> selectByExample(UserFreezeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table u_freeze
     *
     * @mbg.generated
     */
    UserFreeze selectByPrimaryKey(Long uid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table u_freeze
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") UserFreeze record, @Param("example") UserFreezeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table u_freeze
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") UserFreeze record, @Param("example") UserFreezeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table u_freeze
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(UserFreeze record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table u_freeze
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(UserFreeze record);


	       ////*******自定义开始********/
        //***********自定义结束****////
}
