spring:
  datasource:
    # 使用druid数据源
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    druid:
      #监控统计拦截的filters
      filters: stat
      #基本属性
      url: jdbc:mysql://10.1.1.253:3306/chat_monitor?characterEncoding=utf-8
      username: root
      password: hoolai

      max-active: 20
      initial-size: 5
      max-wait: 60000
      min-idle: 5
      timeBetweenEvictionRunsMillis: 60000
      minEvictableIdleTimeMillis: 300000
      validationQuery: select 'x'
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      #打开PSCache，并指定每个连接上PSCache的大小。oracle设为true，mysql设为false。分库分表较多推荐设置为false
      poolPreparedStatements: true
      maxOpenPreparedStatements: 20
mybatis:
  mapper-locations: classpath:mapping/*.xml
  type-aliases-package: com.hoolai.chatmonitor.open.dao.mybatis.vo
  configuration:
    call-setters-on-nulls: true
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql
  row-bounds-with-count: true        

# 打印sql
logging:
  level:
    com.hoolai.chatmonitor.open.dao.mybatis.mapper: debug
