package com.hoolai.chatmonitor.provider.admin.dao.mybatis.vo;

import java.io.Serializable;

@SuppressWarnings("serial")
public class AdminGame  implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin_game.game_id
     *
     * @mbg.generated
     */
    private Long gameId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin_game.game_name
     *
     * @mbg.generated
     */
    private String gameName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin_game.group_id
     *
     * @mbg.generated
     */
    private Integer groupId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin_game.game_id
     *
     * @return the value of admin_game.game_id
     *
     * @mbg.generated
     */
    public Long getGameId() {
        return gameId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin_game.game_id
     *
     * @param gameId the value for admin_game.game_id
     *
     * @mbg.generated
     */
    public void setGameId(Long gameId) {
        this.gameId = gameId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin_game.game_name
     *
     * @return the value of admin_game.game_name
     *
     * @mbg.generated
     */
    public String getGameName() {
        return gameName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin_game.game_name
     *
     * @param gameName the value for admin_game.game_name
     *
     * @mbg.generated
     */
    public void setGameName(String gameName) {
        this.gameName = gameName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin_game.group_id
     *
     * @return the value of admin_game.group_id
     *
     * @mbg.generated
     */
    public Integer getGroupId() {
        return groupId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin_game.group_id
     *
     * @param groupId the value for admin_game.group_id
     *
     * @mbg.generated
     */
    public void setGroupId(Integer groupId) {
        this.groupId = groupId;
    }


	       ////*******自定义开始********/
        //***********自定义结束****////
}
