package com.hoolai.chatmonitor.provider.process.dao.mybatis.mapper;

import com.hoolai.chatmonitor.provider.process.dao.mybatis.vo.MsgSuspicious;
import com.hoolai.chatmonitor.provider.process.dao.mybatis.vo.MsgSuspiciousExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;


public interface MsgSuspiciousMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_suspicious
     *
     * @mbg.generated
     */
    long countByExample(MsgSuspiciousExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_suspicious
     *
     * @mbg.generated
     */
    int deleteByExample(MsgSuspiciousExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_suspicious
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_suspicious
     *
     * @mbg.generated
     */
    int insert(MsgSuspicious record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_suspicious
     *
     * @mbg.generated
     */
    int insertSelective(MsgSuspicious record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_suspicious
     *
     * @mbg.generated
     */
    List<MsgSuspicious> selectByExample(MsgSuspiciousExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_suspicious
     *
     * @mbg.generated
     */
    MsgSuspicious selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_suspicious
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") MsgSuspicious record, @Param("example") MsgSuspiciousExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_suspicious
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") MsgSuspicious record, @Param("example") MsgSuspiciousExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_suspicious
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(MsgSuspicious record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_suspicious
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(MsgSuspicious record);


	       ////*******自定义开始********/
        //***********自定义结束****////
}
