package com.hoolai.chatmonitor.open.dao.mybatis.mapper;

import com.hoolai.chatmonitor.open.dao.mybatis.vo.AdminLog;
import com.hoolai.chatmonitor.open.dao.mybatis.vo.AdminLogExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;


public interface AdminLogMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin_log
     *
     * @mbg.generated
     */
    long countByExample(AdminLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin_log
     *
     * @mbg.generated
     */
    int deleteByExample(AdminLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin_log
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long logId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin_log
     *
     * @mbg.generated
     */
    int insert(AdminLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin_log
     *
     * @mbg.generated
     */
    int insertSelective(AdminLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin_log
     *
     * @mbg.generated
     */
    List<AdminLog> selectByExampleWithBLOBs(AdminLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin_log
     *
     * @mbg.generated
     */
    List<AdminLog> selectByExample(AdminLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin_log
     *
     * @mbg.generated
     */
    AdminLog selectByPrimaryKey(Long logId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin_log
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") AdminLog record, @Param("example") AdminLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin_log
     *
     * @mbg.generated
     */
    int updateByExampleWithBLOBs(@Param("record") AdminLog record, @Param("example") AdminLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin_log
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") AdminLog record, @Param("example") AdminLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin_log
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(AdminLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin_log
     *
     * @mbg.generated
     */
    int updateByPrimaryKeyWithBLOBs(AdminLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin_log
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(AdminLog record);


	       ////*******自定义开始********/
        //***********自定义结束****////
}
