package com.hoolai.chatmonitor.open.dao.mybatis.mapper;

import com.hoolai.chatmonitor.open.dao.mybatis.vo.AdminPermission;
import com.hoolai.chatmonitor.open.dao.mybatis.vo.AdminPermissionExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;


public interface AdminPermissionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin_permission
     *
     * @mbg.generated
     */
    long countByExample(AdminPermissionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin_permission
     *
     * @mbg.generated
     */
    int deleteByExample(AdminPermissionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin_permission
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin_permission
     *
     * @mbg.generated
     */
    int insert(AdminPermission record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin_permission
     *
     * @mbg.generated
     */
    int insertSelective(AdminPermission record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin_permission
     *
     * @mbg.generated
     */
    List<AdminPermission> selectByExample(AdminPermissionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin_permission
     *
     * @mbg.generated
     */
    AdminPermission selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin_permission
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") AdminPermission record, @Param("example") AdminPermissionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin_permission
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") AdminPermission record, @Param("example") AdminPermissionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin_permission
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(AdminPermission record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin_permission
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(AdminPermission record);


	       ////*******自定义开始********/
        //***********自定义结束****////
}
