package com.hoolai.chatmonitor.provider.user.dao.mybatis.vo;

import java.io.Serializable;
import java.util.Date;


@SuppressWarnings("serial")
public class UserFreeze  implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column u_freeze.uid
     *
     * @mbg.generated
     */
    private Long uid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column u_freeze.freezed
     *
     * @mbg.generated
     */
    private Boolean freezed;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column u_freeze.update_time
     *
     * @mbg.generated
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column u_freeze.uid
     *
     * @return the value of u_freeze.uid
     *
     * @mbg.generated
     */
    public Long getUid() {
        return uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column u_freeze.uid
     *
     * @param uid the value for u_freeze.uid
     *
     * @mbg.generated
     */
    public void setUid(Long uid) {
        this.uid = uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column u_freeze.freezed
     *
     * @return the value of u_freeze.freezed
     *
     * @mbg.generated
     */
    public Boolean getFreezed() {
        return freezed;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column u_freeze.freezed
     *
     * @param freezed the value for u_freeze.freezed
     *
     * @mbg.generated
     */
    public void setFreezed(Boolean freezed) {
        this.freezed = freezed;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column u_freeze.update_time
     *
     * @return the value of u_freeze.update_time
     *
     * @mbg.generated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column u_freeze.update_time
     *
     * @param updateTime the value for u_freeze.update_time
     *
     * @mbg.generated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }


	       ////*******自定义开始********/
        //***********自定义结束****////
}
