package com.hoolai.chatmonitor.provider.user.dao.mybatis.vo;

import java.io.Serializable;
import java.util.Date;


@SuppressWarnings("serial")
public class UserLoginInfo  implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column u_login_info.uid
     *
     * @mbg.generated
     */
    private Long uid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column u_login_info.game_id
     *
     * @mbg.generated
     */
    private Long gameId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column u_login_info.game_uid
     *
     * @mbg.generated
     */
    private String gameUid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column u_login_info.create_time
     *
     * @mbg.generated
     */
    private Date createTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column u_login_info.uid
     *
     * @return the value of u_login_info.uid
     *
     * @mbg.generated
     */
    public Long getUid() {
        return uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column u_login_info.uid
     *
     * @param uid the value for u_login_info.uid
     *
     * @mbg.generated
     */
    public void setUid(Long uid) {
        this.uid = uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column u_login_info.game_id
     *
     * @return the value of u_login_info.game_id
     *
     * @mbg.generated
     */
    public Long getGameId() {
        return gameId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column u_login_info.game_id
     *
     * @param gameId the value for u_login_info.game_id
     *
     * @mbg.generated
     */
    public void setGameId(Long gameId) {
        this.gameId = gameId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column u_login_info.game_uid
     *
     * @return the value of u_login_info.game_uid
     *
     * @mbg.generated
     */
    public String getGameUid() {
        return gameUid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column u_login_info.game_uid
     *
     * @param gameUid the value for u_login_info.game_uid
     *
     * @mbg.generated
     */
    public void setGameUid(String gameUid) {
        this.gameUid = gameUid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column u_login_info.create_time
     *
     * @return the value of u_login_info.create_time
     *
     * @mbg.generated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column u_login_info.create_time
     *
     * @param createTime the value for u_login_info.create_time
     *
     * @mbg.generated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }


	       ////*******自定义开始********/
        //***********自定义结束****////
}
